workflows:
  ios-signing:
    name: iOS Signing
    environment:
      groups:
        - ios
    scripts:
      - name: Setup certificate
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/cert.p12
          keychain initialize
          keychain add-certificates \
            --certificate /tmp/cert.p12 \
            --certificate-password "$CM_CERTIFICATE_PASSWORD"
      - name: Show provisioning profile
        script: |
          ls ~/Library/MobileDevice/Provisioning\ Profiles/
    artifacts:
      - ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision
